#!/bin/sh

use() {
	local OPTIND=1
	local opt
	while getopts "hv"; do
		case "$opt" in
			h)
				cat << EOH
Usage: import [options] libname
  options:
  	-h		show this help message and exit
	-v		verbose output
EOH
				;;
		esac
	done
	shift $((OPTIND-1))
	if [ $# -ne 1 ]; then
		echo "import: 1 argument expected, but $# found" >&2
		return 1
	fi
	local name="$1"
	case "name" in
		core::*)
			;;
		ext::*)
			;;
		*)
			;;
	esac
}
